//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteEDMX
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OutboundTrackNTrace : DbContext
    {
        public OutboundTrackNTrace()
            : base("name=OutboundTrackNTrace")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Maritimo> Maritimo { get; set; }
        public virtual DbSet<PortLocation> PortLocation { get; set; }
        public virtual DbSet<TruckOnBoards> TruckOnBoards { get; set; }
        public virtual DbSet<VesselData> VesselData { get; set; }
        public virtual DbSet<VesselLocation> VesselLocation { get; set; }
    }
}
