//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TruckOnBoards
    {
        public int TruckOnBoardId { get; set; }
        public int LicensePlate { get; set; }
        public string TrackNumber { get; set; }
        public System.DateTime DataDeGravacao { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public System.DateTime DataDaLocalizacao { get; set; }
    }
}
