//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class VesselData
    {
        public int VesselDataId { get; set; }
        public string Name { get; set; }
        public string Imo { get; set; }
        public string Mmsi { get; set; }
        public string Indicative { get; set; }
        public string Flag { get; set; }
        public string AisVesselType { get; set; }
        public string Capacity { get; set; }
        public string VesselSize { get; set; }
        public string Year { get; set; }
        public string State { get; set; }
    }
}
